IF
	Global("D5_IWD_REAL","GLOBAL",0)
THEN
	RESPONSE #100
		CutSceneId(Myself)
		ClearAllActions()
		MultiPlayerSync()
		SetGlobal("GEM_TRIGGERED","MYAREA",1)
		MoveViewPoint([166.243],INSTANT)
		MultiPlayerSync()
		ActionOverride(LastTrigger(Myself),FaceObject("AR9603_ATTACK_ME"))
		Wait(1)
		MultiPlayerSync()
		ActionOverride(LastTrigger(Myself),SetSequence(SEQ_ATTACK))
		SmallWait(8)
		EndCutSceneMode()
		ReallyForceSpellRES("IDWI220",Myself)  // Snilloc's Snowball Swarm
		OpenDoor("AR9603_GEM")
		Wait(1)
		MultiPlayerSync()
		AddXP2DA("ID1EX1E")
		MultiPlayerSync()
		DisplayStringPointLog([1195.740],%ilgemeff_strref%)  // No such index
		MultiPlayerSync()
		Wait(1)
END

